const courses = {
  "ba-hons-business-management-with-foundation-year": {
    title: "BA (Hons) Business Management with Foundation Year",
    campus: "David Game College - London",
    type: "2  days per week (daytime or evenings & Saturday)",
    start: "2nd October 2023",
    ucas: "DGBY",
    duration: "4 years",
    level: "Undergraduate",
    body: "Buckinghamshire New University",
    intakes: "March & September",
    overview:
      "The BA (Hons) Business Management with Foundation Year programme is delivered in partnership with Buckinghamshire New University. The course is offered to those who do not meet the minimum requirements for our three-year programme, or those who do not feel fully prepared for first-year entry. This is a four-year programme that includes an initial Foundation Year. The Foundation Year will help you to hone your academic study skills and develop your abilities while also recognising your own strengths and areas for improvement in preparation for a bachelor’s degree. Today’s management of companies and organisations necessitates serious leadership abilities. Companies are still on the lookout for experienced and trained executives to ensure future success. Employers are looking for graduates who are not only academically trained but also work-ready with management and leadership skills. This course will give you the tools you need to be a positive and competent manager. The shift is the only constant for the new generation of executives. This curriculum will not only provide you with experience and understanding of current best practices in strategic international management, but it will also assist you in developing your personal skills in order to prepare you for your first management positions or for starting your own company. This course is delivered two days per week or two evenings plus Saturday. In addition, learners are required to attend a personal tutor meeting twice per semester.",
    module: [
      {
        year: "Foundation Year",
        level: "3",
        modules: [
          { title: "Introduction to Business Studies" },
          { title: "Preparing for Success Knowledge and Creativity" },
          {
            title: "Preparing for Success Self-development and Responsibility",
          },
          { title: "Inquiry Based Learning" },
        ],
      },
      {
        year: "Year 1",
        level: 4,
        modules: [
          { title: "Global Business Environment", credits: 15 },
          { title: "The Graduate Challenge", credits: 15 },
          { title: "Introduction to People Management", credits: 15 },
          { title: "Principles of Marketing", credits: 15 },
          { title: "Financial Decision-making", credits: 15 },
          { title: "Organisational Behaviour", credits: 15 },
          { title: "Career Viewpoint", credits: 15 },
          { title: "Data Insight for Business Decisions", credits: 15 },
        ],
      },
      {
        year: "Year 2",
        level: 5,
        modules: [
          { title: "Business Consulting", credits: 15 },
          { title: "Project Management", credits: 15 },
          { title: "Contemporary Business Economics", credits: 15 },
          { title: "Enterprise and Entrepreneurship", credits: 15 },
          { title: "Consultancy in Practice", credits: 15 },
          { title: "Operations and Service Management", credits: 15 },
          { title: "Digital Business and New Technologies", credits: 15 },
          { title: "Strategic Marketing", credits: 15 },
        ],
      },
      {
        year: "Year 3",
        level: 6,
        modules: [
          { title: "Research Methods", credits: 15 },
          { title: "Strategic Agility", credits: 15 },
          { title: "International Marketing Management", credits: 15 },
          { title: "Developing Leadership & Management Skills", credits: 15 },
          {
            title: "Managing and Developing Innovation & Creativity",
            credits: 15,
          },
          {
            title: "Change Management and Organisation Development",
            credits: 15,
          },
          { title: "Dissertation", credits: 30 },
        ],
      },
    ],
    total_credits: 360,
    entry: [
      "Applications are reviewed individually, considering unique circumstances",
      "Open to applicants with UK qualifications, work experience, or qualifications from overseas",
      "Four-year program available for those who do not meet minimum requirements or need more preparation",
      "Foundation Year applicants typically achieve between 32-56 UCAS tariff points",
      "Suitability for foundation program may vary, contact Admissions team for further discussion",
      "Encourage mature students (21 years and older) to apply, value diverse experiences and perspectives",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students from non-English-speaking countries may need to take an English Test offered by DGHE",
      "Pre-sessional English language course available for those who do not meet required standard",
      "BA (Hons) Business Management with Foundation year qualification requires learners to be 18 years and over at the start of the course",
    ],
  },
  "certificate-in-higher-education-health-and-social-care": {
    title: "Certificate in Higher Education Health and Social Care",
    campus: "David Game College - London",
    type: "Full-time (Daytime or Evenings and Saturdays)",
    start: "2nd October 2023",
    ucas: "(TBC)",
    duration: "9 months",
    level: "Undergraduate",
    body: "University of Gloucestershire",
    intakes: "March & September",
    overview:
      "This course offers a solid foundation for higher education and a career in the UK’s health and social care sector. You will learn about the professions, build academic confidence, and develop the necessary skills to work in this field. Additionally, upon completing the course, you can progress to the BSc (Hons) Health and Social Care Management and Leadership degree delivered at David Game Higher Education, London Campus and awarded by the University of Gloucestershire. Whether you are seeking an exciting and fulfilling career on the frontline of health and social care or are already employed in the field, this course will provide you with the knowledge and experience required to progress academically and professionally. The programme is designed to help you gain expertise in modern health and social care contexts, preparing you for a rewarding professional career in a dynamic and high-demand field. If you are already employed, this course offers the flexibility of a day-release programme, allowing you to continue earning while you study. This course will teach you the essential academic and practical skills to progress to a relevant full-degree programme with the University. Our curriculum includes literacy, numeracy, interpersonal, healthcare and social science knowledge you will need to pursue this career path. You will learn through a mix of active learning in the classroom, online and through Interactive Skills Development Days. Skills Development Days will offer you the opportunity to apply theory to practice in a safe and supportive environment – reflecting on what you do with experienced professionals in real-world settings.",
    module: [
      {
        year: "Year 1",
        level: 4,
        modules: [
          { title: "Reflection in the Workplace 1", credits: 15 },
          {
            title:
              "Applied Numeracy and Literacy Skills for Health and Social Care",
            credits: 15,
          },
          { title: "Healthcare Science in Context", credits: 15 },
          {
            title: "Interpersonal Skills for the Caring Professional",
            credits: 15,
          },
          { title: "Social Science Perspectives", credits: 15 },
          { title: "Anatomy and Physiology", credits: 15 },
          { title: "Introduction to Mental Health", credits: 15 },
          { title: "Policy Context", credits: 15 },
        ],
      },
    ],
    total_credits: 120,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances.",
      "Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- UK or Overseas Qualifications equivalent to Level 3",
      "- Or 48 UCAS Tariff points",
      "- Or 2 A-level standards",
      "For more information on accepted oversea qualifications, visit our designated page.",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "Applicants will undergo an English assessment to help the DGHE academic team evaluate their English level. This will enable DGHE to provide the best support for your academic journey towards achieving success.",
      "Restrictions on learner entry:",
      "The Certificate in Higher Education Health and Social Care requires learners to be 18 years and over at the start of their course.",
    ],
  },
  "higher-national-diploma-art-design": {
    title: "Higher National Diploma in Art & Design",
    campus: "David Game College - London",
    duration: "2 years",
    type: "Full-time Study (Daytime)*",
    level: "RQF Levels 4 and 5",
    start: "2nd October 2023",
    body: "Pearson",
    ucas: "HADG",
    intakes: "March & October",
    overview:
      "The Higher National Diploma in Art & Design at David Game College is a fast track pathway to a successful career in the creative industries. The Graphic Design specialist pathway provides an introduction to a wide range of graphics disciplines, allowing you to specialize in whichever aspect of the graphic design industry you wish to pursue. This course focuses on the development of design skills, practical program knowledge, and technical ability to work in a design environment. You will learn and work with the most up-to-date digital software (Adobe Suite), studying a range of modules that develop skills in digital design, typography, branding, infographics, packaging, motion graphics, illustration, and editorial design. The course is delivered via a combination of Mac studio classes, practical workshops, lectures, one-to-one tutorials, and field trips taken in galleries, street art, and museums. *1st Year 2.5 days in college | 2nd Year 2 days in college (made up to full-time through self-directed study). In addition, learners are required to attend a personal tutor meeting twice per semester.",
    module: [
      {
        year: "Year 1",
        level: 4,
        modules: [
          { title: "Typography", credits: 15 },
          { title: "Graphic Design Practices", credits: 15 },
          { title: "Communication in Art & Design", credits: 15 },
          { title: "Visual Narratives", credits: 15 },
          { title: "Technique and Process", credits: 15 },
          { title: "Professional Practice", credits: 15 },
          { title: "Contextual Studies", credits: 15 },
          { title: "Pearson Set Project", credits: 15 },
        ],
      },
      {
        year: "Year 2",
        level: 5,
        modules: [
          { title: "Advanced Graphic Design", credits: 30 },
          { title: "Digital Animation", credits: 15 },
          { title: "Art Direction", credits: 15 },
          { title: "Branding & Identity", credits: 15 },
          { title: "Professional Practice", credits: 15 },
          { title: "Applied Practice Collaboration Project", credits: 30 },
        ],
      },
    ],
    total_credits: 240,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances.",
      "Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- A level standard or overseas equivalent",
      "- Or other UK level 3 qualifications (e.g. Foundation Diploma, Access to HE Certificate, a BTEC Diploma/National, Advanced GNVQ or AVCE)",
      "- Or Overseas Qualifications equivalent to Level 3 (e.g. Diploma de Baccalaureate, Brandos Atestas, Ensino Medio, etc.)",
      "And a Portfolio of artwork",
      "For more information on accepted international qualifications, visit our designated page.",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements. Usually, students must take an English Test offered by DGHE or provide one of the above.",
      "*If you do not meet the required standard of English requirement in the assessment, you will be offered our Pre-sessional English language course to help you improve your English to the necessary level to gain admission to the degree in Business Management.",
      "Restrictions on learner entry:",
      "The BTEC Higher National qualifications require learners to be 18 years and over at the start of their course.",
    ],
  },
  "btec-hnd-public-service": {
    title: "BTEC HND Public Services",
    campus: "David Game College - London",
    duration: "2 years",
    type: "Full-time (Daytime or Evenings and Saturdays)*",
    level: "RQF Levels 4 and 5",
    start: "25th September 2023",
    body: "Pearson",
    ucas: "HPUB",
    intakes: "January, May & September",
    overview:
      "This course is designed to meet the needs of students wishing to pursue a career in the Public Services sector, most notably the Police Service, Criminal Intelligence, Major Crime Investigation, Crime Analytics, Justice Services such as in Probation / Youth Justice, Security Services Personnel and other Criminal Justice support agencies. You will develop a firm understanding of the Justice system and criminology, human psychology and sociology, diversity, health & safety and your own personal efficiency and development in all situations where crime and criminal services specialists are employed. The Pearson BTEC Level 4 & 5 HNC/D in Public Services provides a specialist, work-related programme of study that covers the key knowledge, understanding and practical skills required for the Public Services sector. There are opportunities for further study and career options. At the end of your course, you will have a recognised qualification which will aid progression into employment in the public services with a particular focus on crime and criminal justice along with other careers that require a disciplined but caring approach. It also offers career progression and professional development for those already in employment. On successful completion of the HND, there is an opportunity to complete a third-year ‘top-up’ with us studying a level 6 BSc (Hons) Criminology & Criminal Justice programme, which is delivered in partnership with the University of Gloucestershire. Alternatively, the HND could lead you to a suitable degree at another provider or graduate entry to selective institutions. This course provides in-depth study of a wide range of public and criminal justice service operations, opportunities to find out about jobs available in these services and prepare you for their entry procedures, regular contact with public service workers and visits to public service providers, assignments and projects directly related to the contemporary public service scene, and practical work on community projects.",
    module: [
      {
        year: "Year 1",
        level: 4,
        modules: [
          { title: "Organisational Structure and Culture", credits: 15 },
          { title: "Mental Health", credits: 15 },
          { title: "Equality and Diversity", credits: 15 },
          { title: "Public Services in Contemporary Society", credits: 15 },
          { title: "Crime Reduction & Community Safety", credits: 15 },
          { title: "Law and Legal Systems", credits: 15 },
          { title: "Third Sector and Public Services", credits: 15 },
          { title: "Psychology of Behaviour", credits: 15 },
        ],
      },
      {
        year: "Year 2",
        level: 5,
        modules: [
          { title: "Reflective Professional Practice", credits: 15 },
          { title: "Youth Offending", credits: 15 },
          { title: "Contemporary Sociological Issues", credits: 15 },
          { title: "Offender Management", credits: 15 },
          { title: "Justice, Punishment and Rehabilitation", credits: 15 },
          { title: "Theories of Crime", credits: 15 },
          { title: "Research Project", credits: 30 },
        ],
      },
    ],
    total_credits: 240,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances.",
      "Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- A level standard or overseas equivalent",
      "- Or other UK level 3 qualifications (e.g. Foundation Diploma, Access to HE Certificate, a BTEC Diploma/National, Advanced GNVQ or AVCE)",
      "- Or Overseas Qualifications equivalent to Level 3 (e.g. Diploma de Baccalaureate, Brandos Atestas, Ensino Medio, etc.)",
      "For more information on accepted international qualifications, visit our designated page.",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements. Usually, students must take an English Test offered by DGHE or provide one of the above.",
      "*If you do not meet the required standard of English requirement in the assessment, you will be offered our Pre-sessional English language course to help you improve your English to the necessary level to gain admission to the degree in Business Management.",
      "Restrictions on learner entry:",
      "The BTEC Higher National qualifications require learners to be 18 years and over at the start of their course.",
    ],
  },
  "btec-hnd-business": {
    title: "BTEC HND Business",
    campus: "David Game College - London",
    duration: "2 years",
    type: "2 days per week (Daytime or Evenings & Saturdays)",
    level: "RQF Levels 4 and 5",
    start: "25th September 2023",
    body: "Pearson",
    ucas: "HBUS",
    intakes: "January, May & September",
    overview:
      "The HND in Business is a major workplace qualification course delivered over two years. It includes a broad range of highly relevant business and management subject areas, making it ideal for those who have started or are planning to move into a private or public sector business career.\n\nThe HND is also recognised as being equivalent to the first two years of a UK degree. HND graduates will therefore gain entry into the third and final year at a university and be able to work toward obtaining a BA Honours Degree in only one further year of study.\n\nThis course is delivered two days per week or two evenings plus Saturday. In addition, learners are required to attend a personal tutor meeting twice per semester.",
    module: [
      {
        year: "Year 1",
        level: 4,
        modules: [
          { title: "Business and Business Environment", credits: 15 },
          { title: "Marketing Processes and Planning", credits: 15 },
          { title: "Human Resource Management", credits: 15 },
          { title: "Leadership and Management", credits: 15 },
          { title: "Accounting Principles", credits: 15 },
          { title: "Managing a Successful Business Project", credits: 15 },
          { title: "Innovation and Commercialisation", credits: 15 },
          { title: "Operations Management", credits: 15 },
        ],
      },
      {
        year: "Year 2",
        level: 5,
        modules: [
          { title: "Research Project", credits: 30 },
          { title: "Organisational Behaviour", credits: 15 },
          { title: "Pitching and Negotiation Skills", credits: 15 },
          { title: "Business Strategy", credits: 15 },
          { title: "Sales Management", credits: 15 },
          { title: "Managing and Running a Small Business", credits: 15 },
          { title: "Statistics for Management", credits: 15 },
        ],
      },
    ],
    total_credits: 240,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances.",
      "Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- A level standard or overseas equivalent",
      "- Or other UK level 3 qualifications (e.g. Foundation Diploma, Access to HE Certificate, a BTEC Diploma/National, Advanced GNVQ or AVCE)",
      "- Or Overseas Qualifications equivalent to Level 3 (e.g. Diploma de Baccalaureate, Brandos Atestas, Ensino Medio, etc.)",
      "For more information on accepted international qualifications, visit our designated page.",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements. Usually, students must take an English Test offered by DGHE or provide one of the above.",
      "*If you do not meet the required standard of English requirement in the assessment, you will be offered our Pre-sessional English language course to help you improve your English to the necessary level to gain admission to the degree in Business Management.",
      "Restrictions on learner entry:",
      "The BTEC Higher National qualifications require learners to be 18 years and over at the start of their course.",
    ],
  },
  "bsc-hons-health-social-care": {
    title: "BSc (Hons) Health and Social Care Leadership and Management",
    campus: "David Game College - London",
    duration: "3 years",
    type: "2 days per week (Daytime or Evenings & Saturdays)",
    level: "Undergraduate",
    start: "October 2024",
    body: "University of Gloucestershire",
    ucas: "N300",
    intakes: "October",
    overview:
      "The demand for care in the UK is growing and is expected to continue to grow. Competent, skilled and knowledgeable leaders and managers are needed at all levels of health and social care to lead healthcare workers and ensure that users continue to receive high-quality care. This degree responds to the growth and demand within the health sector – especially the need for talent and improved standards in management and leadership.\n\nThe BSc (Hons) Health and Social Care Leadership and Management aims to provide students with the underpinning knowledge, skills and values required to work in leadership and management roles in health and social care settings in both acute and community sectors. The course provides students with a range of pathways into careers and further study. The programme aims to ensure that our graduates are employable in more senior and managerial positions within the Health and Social Care sector.\n\nWe designed the overall approach of the programme to stimulate the minds of students who aspire to become leaders and managers within the Health and Social Care sector. The programme builds knowledge and skills, theory and practice of leadership and management. Classes include active engagement in the theoretical problems that impact the sector. Besides the content taught in class, students are expected to spend time reflecting on how learning enables them to develop both academic and practitioner skills as well as independent study.\n\nStudents will be taught using a diverse range of teaching and learning methods, including blended learning experience, flipped learning, group work, seminars, workshops that will be tailored for module-specific help, presentations, simulations and personal one-on-one tutoring by highly competent lecturers with extensive health and social care practice background. Students will be encouraged to critically reflect upon their own practice and consider the role of a leader and manager within the subject area.\n\nThe objectives of the BSc (Hons) Health and Social Care Leadership and Management are as follows:\n\n- Create independent and critically reflective practitioners.\n- Develop practitioners that are resilient and competent leaders and managers who are also capable of ensuring the right skills development and knowledge within their own staff.\n- Provide students with the underpinning knowledge, skills and values required to work in leadership and management roles in health and social care settings in both acute and community settings.\n- Ensure that our graduates are employable in more senior and managerial positions within the Health and Social Care sector.\n- Develop life-long learning which will encourage students to facilitate their own professional development and that of others through reflective practice, education, supervision, feedback and evaluation.\n\nThis course is delivered two days per week or two evenings plus Saturday. In addition to the 2 days of timetabled classes, learners are required to attend a personal tutor meeting twice per semester.",
    module: [
      {
        year: "Year 1",
        level: 4,
        modules: [
          { title: "Health and Social Care in Context", credits: 30 },
          {
            title: "Health and Social Care Policy and Legislation",
            credits: 15,
          },
          {
            title: "Introduction to Management in Health and Social Care",
            credits: 30,
          },
          {
            title: "Communication and Collaboration in Health and Social Care",
            credits: 15,
          },
          { title: "Public Health and Wellbeing", credits: 15 },
          { title: "Reflection and Reflective Practice", credits: 15 },
        ],
      },
      {
        year: "Year 2",
        level: 5,
        modules: [
          { title: "Health Illness and Society", credits: 15 },
          { title: "Management of Resources", credits: 15 },
          { title: "Health Promotion and Wellbeing", credits: 15 },
          {
            title:
              "Management and Leadership Skills in Contemporary Health and Social Care",
            credits: 30,
          },
          {
            title:
              "Quality Management and Service Improvement in Health and Social Care",
            credits: 30,
          },
          { title: "Safeguarding in Health and Social Care", credits: 15 },
        ],
      },
      {
        year: "Year 3",
        level: 6,
        modules: [
          {
            title: "Leading Organisations and Teams in Changing Care Contexts",
            credits: 30,
          },
          {
            title: "Professional Identities, Development and Supervision",
            credits: 15,
          },
          { title: "Comparative Health and Social Care Systems", credits: 15 },
          {
            title:
              "Governance and Regulatory Processes in Health and Social Care",
            credits: 15,
          },
          { title: "Entrepreneurial Skills and Innovation", credits: 15 },
          { title: "Dissertation (choose minimum 30 credits)", credits: 30 },
          {
            title: "Service Improvement Plan (choose minimum 30 credits)",
            credits: 30,
          },
        ],
      },
    ],
    total_credits: 360,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances. Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications",
      "96 UCAS points",
      "Or UK Level 3 qualifications (e.g. Foundation Diploma, Access to HE Certificate, a BTEC Diploma/National, Advanced GNVQ or AVCE)",
      "Overseas Qualifications equivalent to Level 3 (e.g. Diploma de Baccalaureate, Brandos Atestas, Ensino Medio, etc.)",
      "In addition, Maths and English GCSE or equivalent are also required.",
      "Non-standard qualifications & Mature applicants",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "For more information on accepted international qualifications, visit our designated page.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements. Usually, students must take an English Test offered by DGHE or provide one of the above.",
      "*If you do not meet the required standard of English requirement in the assessment, you will be offered our Pre-sessional English language course to help you improve your English to the necessary level to gain admission to the degree in Business Management.",
      "Restrictions on learner entry:",
      "The BSc (Hons) Health and Social Care Leadership and Management requires learners to be 18 years and over at the start of their course.",
    ],
  },
  "ba-hons-business-management": {
    title: "BA (Hons) Business Management",
    campus: "David Game College - London",
    duration: "3 years",
    type: "2 days per week (Daytime or Evenings & Saturdays)",
    level: "Undergraduate",
    start: "2nd October 2023",
    body: "Buckinghamshire New University",
    ucas: "DGBS",
    intakes: "October",
    overview:
      "The BA (Hons) Business Management degree programme is delivered in partnership with Buckinghamshire New University. You will gain a thorough understanding of the essence of business and management in a world of instability, complexity, transition, and ambiguity through this programme.\n\nDeveloping your employability is a key focus of this dynamic and flexible programme. This degree is designed to prepare you to become a confident and skilled business leader; whether your ambitions are for a management career or to start your own business.\n\nIn this course, you learn what’s involved in managing organisations in an increasingly complex world. As well as gaining essential knowledge in marketing, managing operations, accounting and finance, you’ll also develop important management skills that will help you succeed in your business career.\n\nThe underlying principle behind the course content is to mirror the modern business environment, giving you the opportunity to assess solutions to challenging, real-world problems. You’ll learn in small groups and draw on the expertise of lecturers with extensive professional experience in the business sector.\n\nThis undergraduate degree is offered as a full-time study programme for three years as standard, or a four years study option, including a foundation year.\n\nIf you do not meet the minimum requirements for the three-year undergraduate programme or don’t feel fully prepared for a degree course, you can apply for a four-year programme, including a Foundation Year in Business Management.\n\nThe Foundation Year programme aims to deliver a relevant and comprehensive education providing you with a grounding in theory and a great deal of emphasis on the practical side of teaching. If you successfully complete the foundation year with the required grades, you can then progress on to your degree in Business Management.",
    module: [
      {
        year: "Year 1",
        level: 4,
        modules: [
          { title: "Global Business Environment", credits: 15 },
          { title: "The Graduate Challenge", credits: 15 },
          { title: "Introduction to People Management", credits: 15 },
          { title: "Principles of Marketing", credits: 15 },
          { title: "Financial Decision-making", credits: 15 },
          { title: "Organisational Behaviour", credits: 15 },
          { title: "Career Viewpoint", credits: 15 },
          { title: "Data Insight for Business Decisions", credits: 15 },
        ],
      },
      {
        year: "Year 2",
        level: 5,
        modules: [
          { title: "Business Consulting", credits: 15 },
          { title: "Project Management", credits: 15 },
          { title: "Contemporary Business Economics", credits: 15 },
          { title: "Enterprise and Entrepreneurship", credits: 15 },
          { title: "Consultancy in Practice", credits: 15 },
          { title: "Operations and Service Management", credits: 15 },
          { title: "Digital Business and New Technologies", credits: 15 },
          { title: "Strategic Marketing", credits: 15 },
        ],
      },
      {
        year: "Year 3",
        level: 6,
        modules: [
          { title: "Research Methods", credits: 15 },
          { title: "Strategic Agility", credits: 15 },
          { title: "International Marketing Management", credits: 15 },
          { title: "Developing Leadership & Management Skills", credits: 15 },
          {
            title: "Managing and Developing Innovation & Creativity",
            credits: 15,
          },
          {
            title: "Change Management and Organisation Development",
            credits: 15,
          },
          { title: "Dissertation", credits: 30 },
        ],
      },
    ],
    total_credits: 360,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances. Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- A level standard or overseas equivalent to 80 UCAS tariff points",
      "- Other UK level 3 qualifications (e.g. Foundation Diploma, Access to HE Certificate, a BTEC Diploma/National, Advanced GNVQ or AVCE)",
      "- Overseas Qualifications equivalent to Level 3 (e.g. Diploma de Baccalaureate, Brandos Atesta, Estudos Secundários, etc.)",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements. Usually, students must take an English Test offered by DGHE or provide one of the above.",
      "*If you do not meet the minimum requirements for a three-year undergraduate programme or feel you need more preparation for a degree course, you can apply for a four-year programme, including a Foundation with a Year in Business Management.",
      "Restrictions on learner entry:",
      "The BA (Hons) Business Management qualification requires learners to be 18 years and over at the start of their course.",
    ],
  },
  "ba-hons-visual-communication": {
    title: "BA (Hons) Visual Communication (Top-Up)",
    campus: "David Game College - London",
    duration: "1 year",
    type: "Full-time Study (Daytime)*",
    level: "Undergraduate",
    start: "2nd October 2023",
    body: "University of Gloucestershire",
    ucas: "W214",
    intakes: "March & October",
    overview:
      "Our BA Top Up in Visual Communications degree encourages students to explore a diverse range of areas including branding and advertising assignments, developing your creative portfolios, real-world and socially driven design and, undertaking self-initiated projects and individual research determined by your own area of interest whether its branding, typography, illustration, printmaking, or photo documentary. The degree will include modules exploring applied communications and technical skills along with the history and theory of communications in different forms. With new media emerging on a continuous basis, this field changes frequently, but basic principles of good communication remain constant whether the medium is a traditional printed brochure or a mobile advertisement. Students will learn how to communicate ideas effectively across various media and practices, challenging them with new and innovative approaches and analysing the reasoning behind their chosen methods. This will help students produce an interdisciplinary portfolio of artwork that can span a range of areas, including graphic design, illustration, web, moving images, comics, infographics, and packaging. Throughout their course of study, specialist tutors will support students’ work, enabling independent practitioners who are prepared for the world of visual creativity.",
    module: [
      {
        year: "Year 1",
        level: "Undergraduate",
        modules: [
          { title: "Design for the Creative Industry", level: 6, credits: 30 },
          {
            title: "Creative Portfolio",
            level: 6,
            credits: 30,
          },
          {
            title: "Self-Initiated Design Portfolio",
            level: 6,
            credits: 30,
          },
          {
            title: "Dissertation/Major Research Project (MRP)",
            level: 6,
            credits: 30,
          },
        ],
      },
    ],
    total_credits: 120,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances. Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- A pass in a BTEC HND in a relevant field",
      "- A Foundation Degree in a relevant field",
      "- Other Level 5 UK or Overseas qualifications in a related field",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements.",
      "However, if you have previously studied a BTEC HND in an English-speaking country, you will be exempt from taking the English test when applying for a Top-up course.",
    ],
  },
  "bsc-criminology-and-criminal-justice": {
    title: "BSc (Hons) Criminology and Criminal Justice (Top-up)",
    campus: "David Game College - London",
    duration: "1 year",
    type: "2 days per week (Daytime or Evenings and Saturdays)*",
    level: "Undergraduate",
    start: "2nd October 2023",
    body: "University of Gloucestershire",
    ucas: "L311",
    intakes: "March & October",
    overview:
      "BSc (Hons) Criminology and Criminal Justice (Top-up) programme is delivered in partnership with the University of Gloucestershire. The course is designed for students who already have a Foundation Degree, HND, or other qualification in a subject such as criminology, uniformed public services, or criminal justice, and who want to follow a programme of study that takes specialist knowledge and skills to a level relevant for a graduate career in this area. You will follow a programme of study designed to develop critical thinking and research skills, and you will complete an applied research project on a topic of your choice. You will also select four optional modules from a list that is likely to cover topics in policing, restorative justice, homicide, sexual violence, prisons and rehabilitation, and forensic crime scene investigation. You will be supported by a personal tutor who will guide you through the programme and help you plan your next steps after graduation.",
    module: [
      {
        year: "Year 1",
        level: 6,
        modules: [
          {
            title: "Criminal Perspectives on Criminology and Criminal Justice",
            credits: 30,
          },
          { title: "Applied Research Project", credits: 30 },
          { title: "Green Criminology", credits: 15 },
          { title: "Global and Organised Crime", credits: 15 },
          { title: "Injustice and Freedoms", credits: 15 },
          { title: "Restorative Justice", credits: 15 },
        ],
      },
    ],
    total_credits: 120,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances. Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- A pass in a BTEC HND in a relevant field",
      "- A Foundation Degree in a relevant field",
      "- Other Level 5 UK or Overseas qualifications in a related field",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements.",
      "However, if you have previously studied a BTEC HND in an English-speaking country, you will be exempt from taking the English test when applying for a Top-up course.",
    ],
  },
  "ba-hons-business-management-top-up": {
    title: "BA (Hons) Business Management (Top-Up)",
    campus: "David Game College - London",
    duration: "1 year",
    type: "2 days per week (Daytime or Evenings & Saturdays)*",
    level: "Undergraduate",
    start: "02 October 2023",
    body: "Buckinghamshire New University",
    ucas: "DGBU",
    intakes: "March & October",
    overview:
      "In the modern world of complex, fast-paced, and increasingly international business, management skills are essential to realizing your potential in the workplace. The BA (Hons) Business Management (Top Up) course ensures business students have the relevant skills needed to lead change in a dynamic and competitive environment. The one-year course is ideal for those either seeking to start their own business, to be a manager in a national or international setting, or for those that are keen to advance into Postgraduate level study. Our lecturers have extensive industry and academic experience that enhances the delivery of the course, allowing for the practical application in today’s ever-changing business climate. The course will provide all students with the relevant knowledge and skills needed to succeed in an increasingly competitive employment market. The objectives of the BA (Hons) Business Management are to provide all students with in-depth knowledge and understanding of the core functions of business and management, critically evaluate and plan for a range of contemporary business and management scenarios, develop the intellectual skills necessary to contribute to effective business practice and problem-solving, prepare students for graduate employment, research, further study, and lifelong learning by developing their intellectual, practical, and key (transferable) skills, enhance the employability of graduates through the blend of academic study and skills development, and develop enterprise and entrepreneurial skills. In this programme, you will develop a good understanding of the nature of business management. The course will focus on the ability to think critically and will, therefore, enable students to analyze and evaluate solutions to complex, real-life problems.",
    module: [
      {
        year: "Year 1",
        level: 6,
        modules: [
          { title: "Strategic Marketing", credits: 30 },
          { title: "Managing Innovation in Business", credits: 30 },
          { title: "Leading and Managing Change", credits: 30 },
          { title: "Corporate Strategy and Governance", credits: 30 },
        ],
      },
    ],
    total_credits: 120,
    entry: [
      "At DGHE, we review applications individually, considering each applicant’s unique circumstances. Whether you hold a UK qualification, possess work experience or have obtained qualifications from overseas, we are open to discussing your application and exploring potential pathways for admission.",
      "Examples of accepted qualifications:",
      "- A pass in a BTEC HND in a relevant field",
      "- A Foundation Degree in a relevant field",
      "- Other Level 5 UK or Overseas qualifications in a related field",
      "Non-standard qualifications & Mature applicants:",
      "We encourage mature students who are 21 years of age or older to apply. At DGHE, we value mature students’ diverse experiences and perspectives. While some entry requirements may still apply for this programme, we welcome applicants with relevant work experiences and carefully consider each one individually.",
      "English Language Requirements:",
      "IELTS 5.5 / 4/C in English GCSE / Functional Skills Level 2",
      "Students who have studied in a country where English is not the primary language will be required to meet our English Language Requirements.",
      "However, if you have previously studied a BTEC HND in an English-speaking country, you will be exempt from taking the English test when applying for a Top-up course.",
    ],
  },
};

export default courses;
